In [1]:
import pandas as pd
import numpy as np

In [2]:
from numpy import array
from sklearn import linear_model
from sklearn.feature_selection import RFE

In [3]:
%store -r X_train
%store -r X_test
%store -r y_train
%store -r X

In [4]:
log_reg = linear_model.LogisticRegression(random_state=42)

In [5]:
clf = RFE(log_reg, n_features_to_select=1)

In [6]:
trained_model=clf.fit(X_train,y_train)
print(trained_model)

RFE(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=42, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
  n_features_to_select=1, step=1, verbose=0)


In [7]:
y_pred = clf.predict(X_test)

In [8]:
print(clf.support_)

[False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False False False False False False False False False]


In [9]:
rank = clf.ranking_
rank.view()

array([26, 27, 30,  5, 24, 20, 18, 29, 32,  8,  7, 28,  4,  3, 21,  6,  2,
       31, 33, 13, 34,  1, 23, 22, 14, 25, 10, 19, 15,  9, 17, 11, 12, 16])

In [10]:
rank.view()

array([26, 27, 30,  5, 24, 20, 18, 29, 32,  8,  7, 28,  4,  3, 21,  6,  2,
       31, 33, 13, 34,  1, 23, 22, 14, 25, 10, 19, 15,  9, 17, 11, 12, 16])

In [11]:
feature_names = list(X.columns.values)

In [12]:
features = array(feature_names)

In [13]:
features.view()

array(['Age', 'e.BusinessTravel', 'DailyRate', 'e.Department',
       'DistanceFromHome', 'Education', 'e.EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction',
       'e.Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'e.JobRole',
       'JobSatisfaction', 'e.MaritalStatus', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'e.Over18', 'e.OverTime',
       'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='<U24')

In [14]:
con = np.column_stack((rank,features))

In [15]:
con.view()

array([['26', 'Age'],
       ['27', 'e.BusinessTravel'],
       ['30', 'DailyRate'],
       ['5', 'e.Department'],
       ['24', 'DistanceFromHome'],
       ['20', 'Education'],
       ['18', 'e.EducationField'],
       ['29', 'EmployeeCount'],
       ['32', 'EmployeeNumber'],
       ['8', 'EnvironmentSatisfaction'],
       ['7', 'e.Gender'],
       ['28', 'HourlyRate'],
       ['4', 'JobInvolvement'],
       ['3', 'JobLevel'],
       ['21', 'e.JobRole'],
       ['6', 'JobSatisfaction'],
       ['2', 'e.MaritalStatus'],
       ['31', 'MonthlyIncome'],
       ['33', 'MonthlyRate'],
       ['13', 'NumCompaniesWorked'],
       ['34', 'e.Over18'],
       ['1', 'e.OverTime'],
       ['23', 'PercentSalaryHike'],
       ['22', 'PerformanceRating'],
       ['14', 'RelationshipSatisfaction'],
       ['25', 'StandardHours'],
       ['10', 'StockOptionLevel'],
       ['19', 'TotalWorkingYears'],
       ['15', 'TrainingTimesLastYear'],
       ['9', 'WorkLifeBalance'],
       ['17', 'YearsAtCompany

In [16]:
%run Metrics_Evaluation.ipynb

In [17]:
accuracy,cross_validation,mean_square_error,r2_error,confusion_matrix,report=get_metrics(y_pred,clf)

Cross_validation= [ 0.83163265  0.83163265  0.83163265]
Mean_square_error= 0.132653061224
R2_error= -0.152941176471
Confusion_matrix=
 [[255   0]
 [ 39   0]]
Classification_Report=
              precision    recall  f1-score   support

          0       0.87      1.00      0.93       255

avg / total       0.87      1.00      0.93       255



In [18]:
print(accuracy)
print(cross_validation)

0.867346938776
0.831632653061


In [19]:
%store accuracy
%store cross_validation

Stored 'accuracy' (float64)
Stored 'cross_validation' (float64)
