In [1]:
import sklearn

In [3]:
from sklearn import preprocessing

from sklearn.model_selection import train_test_split

from sklearn import linear_model

from sklearn import metrics

from sklearn.metrics import mean_squared_error

from sklearn.metrics import r2_score

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

from sklearn.feature_selection import VarianceThreshold

In [11]:
df = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [12]:
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

           ...           RelationshipSatisfaction StandardHours  \
0          ...                                  1            80   
1          ...                                  4            80   
2          ...                                  2            80   
3          ...                                  3            80   
4          ...                                  4            80   

   StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                  8                      0               1   
1                 1                 10                      3               3   
2                 0                  7                      3               3   
3                 0                  8                      3               3   
4                 1                  6                      3               3   

   YearsAtCompany YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                  4                        0   
1              10                  7                        1   
2               0                  0                        0   
3               8                  7                        3   
4               2                  2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 35 columns]

In [13]:
df

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
5      32        No  Travel_Frequently       1005  Research & Development   
6      59        No      Travel_Rarely       1324  Research & Development   
7      30        No      Travel_Rarely       1358  Research & Development   
8      38        No  Travel_Frequently        216  Research & Development   
9      36        No      Travel_Rarely       1299  Research & Development   
10     35        No      Travel_Rarely        809  Research & Development   
11     29        No      Travel_Rarely        153  Research & Development   
12     31        No      Travel_Rarely        670  Research & Development   
13     34        No      Travel_Rarely       1346  Research & Development   
14     28       Yes      Travel_Rarely        103  Research & Development   
15     29        No      Travel_Rarely       1389  Research & Development   
16     32        No      Travel_Rarely        334  Research & Development   
17     22        No         Non-Travel       1123  Research & Development   
18     53        No      Travel_Rarely       1219                   Sales   
19     38        No      Travel_Rarely        371  Research & Development   
20     24        No         Non-Travel        673  Research & Development   
21     36       Yes      Travel_Rarely       1218                   Sales   
22     34        No      Travel_Rarely        419  Research & Development   
23     21        No      Travel_Rarely        391  Research & Development   
24     34       Yes      Travel_Rarely        699  Research & Development   
25     53        No      Travel_Rarely       1282  Research & Development   
26     32       Yes  Travel_Frequently       1125  Research & Development   
27     42        No      Travel_Rarely        691                   Sales   
28     44        No      Travel_Rarely        477  Research & Development   
29     46        No      Travel_Rarely        705                   Sales   
...   ...       ...                ...        ...                     ...   
1440   36        No  Travel_Frequently        688  Research & Development   
1441   56        No         Non-Travel        667  Research & Development   
1442   29       Yes      Travel_Rarely       1092  Research & Development   
1443   42        No      Travel_Rarely        300  Research & Development   
1444   56       Yes      Travel_Rarely        310  Research & Development   
1445   41        No      Travel_Rarely        582  Research & Development   
1446   34        No      Travel_Rarely        704                   Sales   
1447   36        No         Non-Travel        301                   Sales   
1448   41        No      Travel_Rarely        930                   Sales   
1449   32        No      Travel_Rarely        529  Research & Development   
1450   35        No      Travel_Rarely       1146         Human Resources   
1451   38        No      Travel_Rarely        345                   Sales   
1452   50       Yes  Travel_Frequently        878                   Sales   
1453   36        No      Travel_Rarely       1120                   Sales   
1454   45        No      Travel_Rarely        374                   Sales   
1455   40        No      Travel_Rarely       1322  Research & Development   
1456   35        No  Travel_Frequently       1199  Research & Development   
1457   40        No      Travel_Rarely       1194  Research & Development   
1458   35        No      Travel_Rarely        287  Research & Development   
1459   29        No      Travel_Rarely       1378  Research & Development   
14

In [14]:
df.shape

(1470, 35)

In [15]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [16]:
df[pd.isnull(df).any(axis=1)]

Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager]
Index: []

[0 rows x 35 columns]

In [17]:
le = preprocessing.LabelEncoder()

In [18]:
def encode_col(col_name):
    encodes = le.fit(df[col_name])
    new_col_name = "e."+col_name
    df[new_col_name] = df[col_name].map(lambda x: encodes.transform([x]))
    df[new_col_name] = df[new_col_name].map(lambda x:x[0])
    rle = preprocessing.LabelEncoder()eturn

In [19]:
encode_col('Attrition')

In [20]:
encode_col('BusinessTravel')

In [21]:
encode_col('Department')

In [22]:
encode_col('EducationField')

In [23]:
encode_col('Gender')

In [24]:
encode_col('JobRole')

In [25]:
encode_col('MaritalStatus')

In [26]:
encode_col('Over18')

In [27]:
encode_col('OverTime')

In [28]:
pd.DataFrame(df['Attrition'].value_counts())

Attrition
No        1233
Yes        237

In [29]:
encode_col = le.fit(df['JobRole'])
encode_col.classes_

array(['Healthcare Representative', 'Human Resources',
       'Laboratory Technician', 'Manager', 'Manufacturing Director',
       'Research Director', 'Research Scientist', 'Sales Executive',
       'Sales Representative'], dtype=object)

In [30]:
encode_col = le.fit(df['MaritalStatus'])
encode_col.classes_

array(['Divorced', 'Married', 'Single'], dtype=object)

In [31]:
encode_col = le.fit(df['Over18'])
encode_col.classes_

array(['Y'], dtype=object)

In [32]:
encode_col = le.fit(df['OverTime'])
encode_col.classes_

array(['No', 'Yes'], dtype=object)

# Split Dependent and independent variables

In [33]:
X = df[["Age","e.BusinessTravel","DailyRate","e.Department","DistanceFromHome","Education","e.EducationField",'EmployeeCount',"EmployeeNumber","EnvironmentSatisfaction","e.Gender","HourlyRate","JobInvolvement","JobLevel","e.JobRole","JobSatisfaction","e.MaritalStatus","MonthlyIncome","MonthlyRate","NumCompaniesWorked","e.Over18","e.OverTime","PercentSalaryHike","PerformanceRating","RelationshipSatisfaction","StandardHours","StockOptionLevel","TotalWorkingYears","TrainingTimesLastYear","WorkLifeBalance","YearsAtCompany","YearsInCurrentRole","YearsSinceLastPromotion","YearsWithCurrManager"]]

In [34]:
y = df["e.Attrition"]

In [35]:
type(X)

pandas.core.frame.DataFrame

In [36]:
X.shape

(1470, 34)

In [37]:
type(y)

pandas.core.series.Series

In [38]:
y.shape

(1470,)

# Split training and testing data

In [39]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20,random_state = 4)

In [40]:
X_train.shape

(1176, 34)

In [41]:
X_test.shape

(294, 34)

In [42]:
y_train.shape

(1176,)

In [43]:
y_test.shape

(294,)

In [44]:
reg = linear_model.LogisticRegression()

In [45]:
trained_model=reg.fit(X_train,y_train)

In [46]:
reg.intercept_

array([ 0.00065983])

In [47]:
reg.coef_

array([[ -4.42347501e-02,  -6.35507946e-03,  -3.29266966e-04,
          2.39638094e-01,   2.31139682e-02,   3.72674913e-02,
          4.34217587e-02,   6.59830979e-04,  -1.24900504e-04,
         -3.65987061e-01,   1.83053027e-01,  -9.20494865e-04,
         -4.13965425e-01,  -7.22084399e-02,   1.58260386e-02,
         -4.14383534e-01,   4.35087216e-01,  -6.58069026e-05,
          5.37747137e-06,   1.63993191e-01,   0.00000000e+00,
          1.11770110e+00,  -2.60134178e-02,   8.05495261e-02,
         -2.25857906e-01,   5.27864783e-02,  -1.91132078e-01,
         -3.84639542e-02,  -1.59824559e-01,  -2.76699466e-01,
          7.94095828e-02,  -1.16419570e-01,   1.05421607e-01,
         -1.13649848e-01]])

In [48]:
X_test.head()

Age  e.BusinessTravel  DailyRate  e.Department  DistanceFromHome  \
325    31                 1        798             1                 7   
1165   44                 1        602             0                 1   
1153   18                 1        544             2                 3   
1403   39                 2        119             2                15   
1019   36                 2        329             2                16   

      Education  e.EducationField  EmployeeCount  EmployeeNumber  \
325           2                 1              1             442   
1165          5                 0              1            1642   
1153          2                 3              1            1624   
1403          4                 2              1            1975   
1019          4                 2              1            1436   

      EnvironmentSatisfaction          ...           RelationshipSatisfaction  \
325                         3          ...                                  1   
1165                        1          ...                                  3   
1153                        2          ...                                  3   
1403                        2          ...                                  1   
1019                        3          ...                                  1   

      StandardHours  StockOptionLevel  TotalWorkingYears  \
325              80                 1                 10   
1165             80                 0                 14   
1153             80                 0                  0   
1403             80                 0                 21   
1019             80                 2                 11   

      TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
325                       2                3              10   
1165                      3                3              10   
1153                      2                4               0   
1403                      3                3              20   
1019                      3                2               3   

      YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
325                    9                        8                     9  
1165                   7                        0                     2  
1153                   0                        0                     0  
1403                   8                       11                    10  
1019                   2                        0                     2  

[5 rows x 34 columns]

In [49]:
y_test.head()

325     0
1165    0
1153    1
1403    0
1019    0
Name: e.Attrition, dtype: int64

In [50]:
reg.predict([[31,1,798,1,7,2,1,1,442,3,0,48,2,3,4,3,1,8943,14034,1,0,0,24,4,1,80,1,10,2,3,10,9,8,9]])

array([0], dtype=int64)

In [51]:
reg.predict([[18,1,544,2,3,2,3,1,1624,2,0,70,3,1,8,4,2,1569,18420,1,0,1,12,3,3,80,0,0,2,4,0,0,0,0]])

array([1], dtype=int64)

In [52]:
y_pred = reg.predict(X_test)

In [53]:
type(y_pred)

numpy.ndarray

In [54]:
len(y_pred)

294

In [55]:
y_test_m = y_test.as_matrix()

In [56]:
type(y_test_m)

numpy.ndarray

# Analaysis

In [64]:
reg = linear_model.LogisticRegression()
trained_model=reg.fit(X_train,y_train)

In [88]:
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy=",accuracy)
%store accuracy
cross_validation=accuracy_score(y_train,trained_model.predict(X_train))
print("Cross Validation=",cross_validation)

Accuracy= 0.897959183673
Stored 'accuracy' (float64)
Cross Validation= 0.871598639456


In [85]:
m_error=mean_squared_error(y_test,y_pred) 
print (m_error)

0.102040816327


In [86]:
r2_error=r2_score(y_test,y_pred)
print(r2_error)

0.182803669045


In [87]:
matrix=confusion_matrix(y_test,y_pred)
print(matrix)

[[248   3]
 [ 27  16]]


In [63]:
report = classification_report(y_test,y_pred)
print(report)

             precision    recall  f1-score   support

          0       0.90      0.99      0.94       251
          1       0.84      0.37      0.52        43

avg / total       0.89      0.90      0.88       294

