In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel

In [2]:
df = pd.read_csv("Dataset 2.csv")

In [3]:
le = preprocessing.LabelEncoder()

In [4]:
def encode_col(col_name):
    encodes = le.fit(df[col_name])
    new_col_name = "e."+col_name
    df[new_col_name] = df[col_name].map(lambda x: encodes.transform([x]))
    df[new_col_name] = df[new_col_name].map(lambda x:x[0])
    return

In [5]:
encode_col('Attrition')
encode_col('BusinessTravel')
encode_col('Department')
encode_col('EducationField')
encode_col('Gender')
encode_col('JobRole')
encode_col('MaritalStatus')
encode_col('Over18')
encode_col('OverTime')

In [6]:
X = df[["Age","e.BusinessTravel","DailyRate","e.Department","DistanceFromHome","Education","e.EducationField",'EmployeeCount',"EmployeeNumber","EnvironmentSatisfaction","e.Gender","HourlyRate","JobInvolvement","JobLevel","e.JobRole","JobSatisfaction","e.MaritalStatus","MonthlyIncome","MonthlyRate","NumCompaniesWorked","e.Over18","e.OverTime","PercentSalaryHike","PerformanceRating","RelationshipSatisfaction","StandardHours","StockOptionLevel","TotalWorkingYears","TrainingTimesLastYear","WorkLifeBalance","YearsAtCompany","YearsInCurrentRole","YearsSinceLastPromotion","YearsWithCurrManager"]]

In [7]:
y = df["e.Attrition"]

In [8]:
X.shape

(1470, 34)

In [9]:
X.head

<bound method NDFrame.head of       Age  e.BusinessTravel  DailyRate  e.Department  DistanceFromHome  \
0      41                 2       1102             2                 1   
1      49                 1        279             1                 8   
2      37                 2       1373             1                 2   
3      33                 1       1392             1                 3   
4      27                 2        591             1                 2   
5      32                 1       1005             1                 2   
6      59                 2       1324             1                 3   
7      30                 2       1358             1                24   
8      38                 1        216             1                23   
9      36                 2       1299             1                27   
10     35                 2        809             1                16   
11     29                 2        153             1                15   
12     3

In [10]:
type(X)

pandas.core.frame.DataFrame

In [11]:
clf = ExtraTreesClassifier()

In [12]:
clf = clf.fit(X, y)

In [13]:
clf.feature_importances_ 

array([ 0.04110316,  0.01881797,  0.03174338,  0.02467708,  0.03536687,
        0.02398398,  0.03115683,  0.        ,  0.02986053,  0.03931406,
        0.01769396,  0.02878321,  0.02859532,  0.02509625,  0.0347258 ,
        0.03546272,  0.03944241,  0.04712795,  0.02638717,  0.037857  ,
        0.        ,  0.06718725,  0.03145642,  0.01681241,  0.0287303 ,
        0.        ,  0.03363089,  0.04065197,  0.0273362 ,  0.03228231,
        0.03685827,  0.02932545,  0.0230164 ,  0.03551646])

In [14]:
model = SelectFromModel(clf, prefit=True)

In [15]:
X_new = model.transform(X)

In [30]:
X_new.shape

(1470, 18)

In [31]:
X_new.shape[1] #column size

18

In [17]:
type(X_new)

numpy.ndarray

In [18]:
X_new.view()

array([[  41, 1102,    1, ...,    1,    6,    5],
       [  49,  279,    8, ...,    3,   10,    7],
       [  37, 1373,    2, ...,    3,    0,    0],
       ..., 
       [  27,  155,    4, ...,    3,    6,    3],
       [  49, 1023,    2, ...,    2,    9,    8],
       [  34,  628,    8, ...,    4,    4,    2]], dtype=int64)

In [19]:
#X_nd = X.values

In [20]:
#type(X_nd)

In [21]:
#X_nd.view()

In [22]:
#X_new_df = pd.DataFrame(data=X_new[1:,1:], index=X_new[1:,0], columns=X_new[0,1:])

In [23]:
#type(X_new_df)

In [32]:
X_new[0,:]

array([  41, 1102,    1,    1,    1,    2,    7,    4,    2, 5993,    8,
          1,   11,    0,    8,    1,    6,    5], dtype=int64)

In [33]:
X_new[1,:]

array([  49,  279,    8,    1,    2,    3,    6,    2,    1, 5130,    1,
          0,   23,    1,   10,    3,   10,    7], dtype=int64)

In [34]:
X_new[2,:]

array([  37, 1373,    2,    4,    4,    4,    2,    3,    2, 2090,    6,
          1,   15,    0,    7,    3,    0,    0], dtype=int64)

In [35]:
X_new[3,:]

array([  33, 1392,    3,    1,    5,    4,    6,    3,    1, 2909,    1,
          1,   11,    0,    8,    3,    8,    0], dtype=int64)

In [26]:
#features = np.array(["Age","DailyRate","DistanceFromHome","EmployeeNumber","EnvironmentSatisfaction","HourlyRate","JobInvolvement","JobLevel","e.JobRole","JobSatisfaction","e.MaritalStatus","MonthlyIncome","MonthlyRate","NumCompaniesWorked","e.OverTime","RelationshipSatisfaction","StockOptionLevel","TotalWorkingYears","TrainingTimesLastYear","WorkLifeBalance","YearsAtCompany","YearsInCurrentRole"])

In [27]:
#features.shape

In [28]:
#X_withf = np.vstack((features,X_new))